### PR TITLE
changed texture, cars and signs on sprite sheet

### PR DESCRIPTION
**Pull request by PenguinFlyingHigh**

### CODE REVIEW

**Comment by PenguinFlyingHigh** [comment]
Cars at 100x50px
Signs are 25x25px

**Comment by nikrolas** [comment]
Looks like this is just changes to assets. If we merge this branch, is there anything that needs to be changed in the code?

**Review by theochit — APPROVED** [review]
the new cars look great, but I think it might be nice to have something a little more simple on the eyes than a turning sign. I think something simple like this might look a little clearer when there are up to 8 different directions showing on screen: https://www.google.com/search?q=left+arrow+yellow&safe=off&client=firefox-b-ab&source=lnms&tbm=isch&sa=X&ved=0ahUKEwjS8cromK7ZAhXOwVkKHYdVC3kQ_AUICigB&biw=1920&bih=943#imgrc=6F11cYGEvm2jxM: 
Another little benefit is only needing one asset for all directions, but that's obviously pretty minor

**Comment by PenguinFlyingHigh** [comment]
I've left the redcar.png in for now, but we'll eventually change the code so that we pull the picture off this sprite sheet rather than one texture per car.

**Comment by PenguinFlyingHigh** [comment]
Let's keep the yellow triangle for now, and see how that works with the placard. If it's hard to on the eyes, I think we can easily change to the yellow arrow!

**Pull request merged**
